language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
  
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

addons:
  code_climate:
    repo_token: a49b7d669fc78064872a1cb69df48722827d05d456e80ecbbd10bcf6c0c9b278